// log
export const GET_PRODUCTS = "GET_PRODUCTS"
export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"

// set state
export const SET_PRODUCTS = "SET_PRODUCTS"
export const SET_NEW_PRODUCT = "SET_NEW_PRODUCT"
export const SET_UPDATED_PRODUCT = "SET_UPDATED_PRODUCT"
export const SET_DELETE_PRODUCT = "SET_DELETE_PRODUCT"
